package com.example.recyclingapp.dataClasses.ai

import AIResponse
import com.example.recyclingapp.dataClasses.ai.dataClasses.AIRequest
import retrofit2.http.Body
import retrofit2.http.POST
import retrofit2.http.Query

/**
 * Retrofit interface used to SEND chat requests to the AI service.
 *
 * Sends an AIRequest to the /v1/chat/completions endpoint and returns
 * the AIResponse generated by the model.
 */
interface AIRetrofitApi {
    @POST("models/gemini-1.5-flash-latest:generateContent")
    suspend fun askAI(
        @Body request: AIRequest
    ): AIResponse
}
